### ISSUE TITLE
Add confirm modal for publish or unpublish all

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/cartographer_frontend#23]
When a user clicks publish or unpublish on a map, the desired behavior is for all resource records in ArchivesSpace associated with the map as components to be published or unpublished in AS as well.

A confirm modal needs to be added so that users are aware of this action, and can either confirm or cancel.

**Comment by HaSistrunk** [comment]
@helrond did this work for you when you tested? I'm not getting a modal popping up with the Publish or Unpublish buttons
