### ISSUE TITLE
Improve keyboard accessibility of tree

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/cartographer_frontend#47]
The tree view does not support keyboard-only use. Research [Dragon Drop](https://github.com/schne324/dragon-drop) as a solution.

**Comment by HaSistrunk** [comment]
I think along with keyboard accessibility, we'll need to think about screen reader accessibility with this. I tested this with VoiceOver, and it
1. called the tree "grid", which I think is an aria-label issue
2. treated the tree as a table with 0 columns and 0 rows. 
3. It couldn't access/read the component title text
4. There is keyboard focus on the expand/collapse and the add child - edit - delete buttons, but the screen reader just reads the button text without associating those interactive elements with the component they are related to.

**Comment by helrond** [comment]
In addition [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) seems like a good option.

**Comment by helrond** [comment]
As far as I can tell, the more accessible options do not support drag and drop across multiple levels of a tree. After conversations with the primary user for this application, it was determined that functionality which supports dragging and dropping across multiple levels is more important than keyboard navigability or screen reader output. So I've added some information about the known accessibility issues to the readme, and am closing this issue.
